file = open("C:/Users/Naveen kuruva/Desktop/names.txt", "w")
print("File path  :", file.name)
print("Mode       :", file.mode)
print("File closed?", file.closed)
file.close()
print("File closed?", file.closed)
